version: 2

models:
  - name: int_user_orders
    description: Intermediary table of User Statistics on purchases done
    columns:
      - name: user_id
        tests:
          - not_null
      - name: avg_order_cost
        tests:
          - not_null
          - positive_values
      - name: orders_done
        tests:
          - not_null
          - positive_values

  - name: int_orders_extended
    description: Enriched table of orders with Address,-user,-promo metadata
    columns:
      - name: order_id 
        tests:
          - unique
          - not_null
      - name: user_id
        tests:
          - not_null

  - name: int_events_extended
    description: Enriched table of events with product name
    columns:
      - name: session_id 
        tests:
          - not_null
      - name: user_id 
        tests:
          - not_null
  
  - name: fct_shipping_services
    description: Aggregated Orders by shipping services.. can be expanded to identify high costs per state etc...
    columns:
      - name: shipping_service
        tests:
          - not_null


  - name: int_sessions_users_products_aggregated
    description: Aggregated table per session, per user, per product. Will assist for further product analysis

  - name: int_sessions_users_aggregated
    description: Aggregated table per session, per user, with some aggregations for funnel analysis
    columns:
      - name: page_view
        description: column depicting page_views. We check if this event occurs, if it's not there, we have a tracking issue.
        tests:
        - dbt_expectations.expect_column_to_exist

  - name: int_order_products
    description: Overall product orders done, and amounts sold.


macros:
  - name: event_type_loop
    description: A macro that generates dynamically columns based on a predefined event-type array.